# Generated by Django 6.1 on 2026-08-29 20:25

import linkedin.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='state',
            field=models.CharField(choices=[('Qualified', 'Qualified'), ('Ready to Connect', 'Ready to Connect'), ('Pending', 'Pending'), ('Connected', 'Connected'), ('Handoff', 'Handoff'), ('Completed', 'Completed'), ('Failed', 'Failed')], default=linkedin.enums.ProfileState['QUALIFIED'], max_length=20),
        ),
    ]
