# Generated by Django 6.0.6 on 2026-06-24 05:18

import django.db.models.deletion
import linkedin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0015_seed_campaign_prompt_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='browser_has_touch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='browser_is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='browser_locale',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='browser_timezone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='browser_user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='browser_viewport_height',
            field=models.PositiveIntegerField(default=768),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='browser_viewport_width',
            field=models.PositiveIntegerField(default=1365),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='cookie_import_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='cookie_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_text',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='cta',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='post',
            name='image_template_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='include_hashtags',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=32),
        ),
        migrations.AddField(
            model_name='post',
            name='media_mode',
            field=models.CharField(choices=[('none', 'No image'), ('template', 'Template cover'), ('ai', 'AI generated image'), ('uploaded', 'Uploaded image')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('imported', 'Imported'), ('generated_topic', 'Generated Topic')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('follow_up', 'Follow Up'), ('publish_post', 'Publish Post')], max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cover_text_prompt_template',
            field=models.TextField(blank=True, default=linkedin.models._default_cover_text_prompt_template, help_text='Промпт для AI, который пишет короткую фразу-подпись (5–9 слов) поверх Figma-обложки.\n\nПодстановки:\n  • {post_text} — уже сгенерированный текст поста\n  • {topic} — тема (из Post Topic)\n  • {language} — язык (из настройки Post language)\n\nЕсли очистить поле и сохранить — снова появится дефолт.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='post_prompt_template',
            field=models.TextField(blank=True, default=linkedin.models._default_post_prompt_template, help_text='Системный промпт для AI-генератора текста поста. Пишется как обычный текст с подстановками в фигурных скобках, например {topic} или {product_docs}.\n\nПодстановки:\n  • {self_name} — имя автора (из LinkedIn-профиля бота)\n  • {product_docs} — описание компании (поле выше)\n  • {post_system_prompt} — правила стиля (поле выше)\n  • {topic} — тема конкретного поста (из Post Topic)\n  • {language} — язык (из настройки Post language)\n  • {hashtags_instruction} — инструкция «добавь N хэштегов» (автоматически собирается)\n  • {cta_instruction} — инструкция «добавь CTA» (если задан)\n\nЕсли очистить поле и сохранить — снова появится дефолт.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='approval_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='llm_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('groq', 'Groq'), ('mistral', 'Mistral'), ('cohere', 'Cohere'), ('openai_compatible', 'OpenAI-compatible'), ('codex', 'Codex CLI')], default='openai', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('connect', 'Connect'), ('check_pending', 'Check Pending'), ('follow_up', 'Follow Up'), ('generate_post', 'Generate Post'), ('publish_post', 'Publish Post')], max_length=20),
        ),
        migrations.CreateModel(
            name='PostTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('include_hashtags', models.BooleanField(default=True)),
                ('hashtags_count', models.PositiveSmallIntegerField(default=3)),
                ('cta', models.TextField(blank=True, default='')),
                ('media_mode', models.CharField(choices=[('none', 'No image'), ('template', 'Template cover'), ('ai', 'AI generated image'), ('uploaded', 'Uploaded image')], default='none', max_length=20)),
                ('image_template_key', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('imported', 'Imported'), ('generated', 'Generated')], default='manual', max_length=20)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_topics', to='linkedin.campaign')),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_request', to='linkedin.post')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['campaign', 'consumed_at', 'created_at'], name='linkedin_po_campaig_b05040_idx')],
            },
        ),
    ]
