# Generated by Django 6.1 on 2026-08-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0016_linkedinprofile_browser_has_touch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='qualifying_question',
            field=models.TextField(blank=True, default='', help_text='Целевой вопрос, к которому бот переходит, как только лид дал содержательный ответ. Формулируется как намерение, а не как скрипт — бот переписывает его своими словами на языке лида и привязывает к тому, что тот только что рассказал.\n\nОставьте поле пустым, чтобы использовать общий вопрос из репозитория: тогда правка в коде приезжает на все аккаунты сама, и три базы не расходятся. Заполняйте только если этой кампании нужен свой вопрос.'),
        ),
    ]
