# Generated by Django 6.1 on 2026-09-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0017_campaign_qualifying_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brand_name',
            field=models.CharField(blank=True, default='', help_text='Название компании ровно в том виде, в каком оно должно стоять в сообщениях. По нему же определяется, представились мы уже или нет. Пусто — берётся из репозитория.', max_length=120),
        ),
        migrations.AddField(
            model_name='campaign',
            name='handover_contacts',
            field=models.TextField(blank=True, default='', help_text='Телефон / Telegram, которые бот даёт лиду при переводе на человека. Пока пусто — бот просит контакт у лида, а свой не называет.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='self_introduction',
            field=models.TextField(blank=True, default='', help_text='Как бот представляется после ответа на целевой вопрос. Одна-две фразы, по делу. Пусто — берётся общий текст из репозитория.'),
        ),
    ]
