# Generated by Django 6.1 on 2026-09-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0018_campaign_intro_and_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='profile_view_daily_limit',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='profile_view_hourly_limit',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linkedin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='linkedin.linkedinprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['linkedin_profile', 'created_at'], name='linkedin_pr_linkedi_694237_idx')],
            },
        ),
    ]
